name: C Application CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential expect

    - name: Build your project
      run: |
        cd ConsoleApplication1
        gcc ConsoleApplication1.c -o myapp

    - name: Set execute permission for the expect script
      run: chmod +x ./ConsoleApplication1/run_myapp.expect

    - name: Run application with expect
      run: |
        ./ConsoleApplication1/run_myapp.expect

    # - name: Check console output
    #   run: diff actual_console_output.txt tests/expected_console_output.txt

    - name: Check output file
      run: diff test.txt tests/expected_test.txt
